"""Knowledge-graph builder with LLM profiling and incremental updates.

Features:
- Full graph construction from document chunks (existing).
- LLM profiling: generate searchable key-value pairs for entities and relations.
- Incremental updates: set-union merge of new entities/relations without reindex.
"""

import asyncio
import json
import logging
import re
import uuid
from datetime import datetime, timezone
from typing import Callable, Optional

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# Pattern for validating entity types / relation types from LLM output
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_MAX_ENTITIES = 50
_MAX_RELATIONS = 50


# ---------------------------------------------------------------------------
# Domain models
# ---------------------------------------------------------------------------

class EntityProfile(BaseModel):
    """Searchable key-value profile generated by the LLM for a graph entity."""
    entity_name: str
    entity_type: str = ""
    keywords: list[str] = Field(default_factory=list)
    summary: str = ""
    attributes: dict[str, str] = Field(default_factory=dict)


class RelationProfile(BaseModel):
    """Searchable key-value profile generated by the LLM for a graph relation."""
    from_entity: str
    to_entity: str
    relation_type: str = ""
    keywords: list[str] = Field(default_factory=list)
    summary: str = ""
    attributes: dict[str, str] = Field(default_factory=dict)


class GraphUpdateMeta(BaseModel):
    """Metadata tracking an incremental graph update."""
    source_document: str = ""
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )
    entities_added: int = 0
    relations_added: int = 0
    entities_merged: int = 0
    relations_merged: int = 0


# ---------------------------------------------------------------------------
# KnowledgeGraphBuilder
# ---------------------------------------------------------------------------

class KnowledgeGraphBuilder:
    """Build and maintain a knowledge graph from document chunks.

    Parameters
    ----------
    graph_store :
        Object with ``build_graph_from_entities``, ``search_nodes``,
        ``create_node``, ``create_relation`` async methods.
    llm_adapter : optional
        Object with an ``async chat(messages, ...)`` method.
    """

    def __init__(self, graph_store, llm_adapter=None):
        self.graph_store = graph_store
        self.llm_adapter = llm_adapter

    # ------------------------------------------------------------------
    # Full graph construction (existing)
    # ------------------------------------------------------------------

    async def build_graph(
        self,
        chunks: list[dict],
        batch_size: int = 5,
        concurrency_limit: int = 3,
        progress_callback: Callable = None,
        cancel_check: Callable = None,
    ) -> dict:
        semaphore = asyncio.Semaphore(concurrency_limit)
        total = len(chunks)
        processed = 0
        all_entities = []
        all_relations = []

        async def process_chunk(chunk: dict):
            nonlocal processed
            if cancel_check and cancel_check():
                return {"entities": [], "relations": []}

            async with semaphore:
                entities, relations = await self._extract_entities(
                    chunk.get("content", ""),
                )
                processed += 1
                if progress_callback:
                    progress_callback(processed / total)
                return {"entities": entities, "relations": relations}

        for i in range(0, len(chunks), batch_size):
            if cancel_check and cancel_check():
                break
            batch = chunks[i: i + batch_size]
            results = await asyncio.gather(
                *[process_chunk(c) for c in batch], return_exceptions=True,
            )
            for r in results:
                if isinstance(r, dict):
                    all_entities.extend(r["entities"])
                    all_relations.extend(r["relations"])

        node_ids = await self.graph_store.build_graph_from_entities(
            all_entities, all_relations,
        )

        return {
            "entities_count": len(all_entities),
            "relations_count": len(all_relations),
            "node_ids": node_ids,
        }

    # ------------------------------------------------------------------
    # LLM Profiling
    # ------------------------------------------------------------------

    async def profile_entity(self, entity: dict) -> EntityProfile:
        """Use the LLM to generate searchable key-value pairs for an entity.

        Parameters
        ----------
        entity : dict
            Must contain at least ``name``. May contain ``type``, ``description``.

        Returns
        -------
        EntityProfile with keywords, summary, and attributes.
        """
        name = entity.get("name", "")
        etype = entity.get("type", "Entity")
        description = entity.get("description", "")

        if not self.llm_adapter:
            return self._heuristic_entity_profile(name, etype, description)

        prompt = (
            "请为以下知识图谱实体生成可搜索的描述信息。"
            "严格返回如下 JSON 格式，不要附加任何其他文本：\n"
            '{"keywords": ["关键词1", ...], '
            '"summary": "一句话摘要", '
            '"attributes": {"属性名": "属性值", ...}}\n\n'
            f"实体名称：{name}\n"
            f"实体类型：{etype}\n"
            f"描述：{description}"
        )

        try:
            response = await self.llm_adapter.chat(
                messages=[{"role": "user", "content": prompt}],
                model=None,
                temperature=0.0,
                max_tokens=500,
            )
            data = self._parse_json_response(response.content)
            return EntityProfile(
                entity_name=name,
                entity_type=etype,
                keywords=data.get("keywords", []),
                summary=data.get("summary", ""),
                attributes=data.get("attributes", {}),
            )
        except Exception:
            logger.warning("LLM entity profiling failed for '%s'", name)
            return self._heuristic_entity_profile(name, etype, description)

    async def profile_relation(self, relation: dict) -> RelationProfile:
        """Use the LLM to generate searchable key-value pairs for a relation.

        Parameters
        ----------
        relation : dict
            Must contain ``from_entity`` and ``to_entity``.
            May contain ``relation_type``, ``description``.

        Returns
        -------
        RelationProfile with keywords, summary, and attributes.
        """
        from_e = relation.get("from_entity", "")
        to_e = relation.get("to_entity", "")
        rel_type = relation.get("relation_type", "RELATED_TO")
        description = relation.get("description", "")

        if not self.llm_adapter:
            return self._heuristic_relation_profile(
                from_e, to_e, rel_type, description,
            )

        prompt = (
            "请为以下知识图谱关系生成可搜索的描述信息。"
            "严格返回如下 JSON 格式，不要附加任何其他文本：\n"
            '{"keywords": ["关键词1", ...], '
            '"summary": "一句话摘要", '
            '"attributes": {"属性名": "属性值", ...}}\n\n'
            f"源实体：{from_e}\n"
            f"目标实体：{to_e}\n"
            f"关系类型：{rel_type}\n"
            f"描述：{description}"
        )

        try:
            response = await self.llm_adapter.chat(
                messages=[{"role": "user", "content": prompt}],
                model=None,
                temperature=0.0,
                max_tokens=500,
            )
            data = self._parse_json_response(response.content)
            return RelationProfile(
                from_entity=from_e,
                to_entity=to_e,
                relation_type=rel_type,
                keywords=data.get("keywords", []),
                summary=data.get("summary", ""),
                attributes=data.get("attributes", {}),
            )
        except Exception:
            logger.warning("LLM relation profiling failed for '%s->%s'", from_e, to_e)
            return self._heuristic_relation_profile(
                from_e, to_e, rel_type, description,
            )

    # ------------------------------------------------------------------
    # Incremental updates
    # ------------------------------------------------------------------

    async def incremental_update(
        self,
        new_entities: list[dict],
        new_relations: list[dict],
        source_document: str = "",
    ) -> GraphUpdateMeta:
        """Merge new entities and relations into the existing graph.

        Uses set-union semantics: if an entity with the same ``name`` already
        exists, its properties are updated (not replaced). New nodes and edges
        are simply appended. No full reindex is performed.

        Parameters
        ----------
        new_entities : list[dict]
            Entities to merge. Each must have at least ``name``.
        new_relations : list[dict]
            Relations to merge. Each must have ``from_entity``, ``to_entity``.
        source_document : str
            Document identifier that produced these elements.

        Returns
        -------
        GraphUpdateMeta with counts of added/merged elements.
        """
        meta = GraphUpdateMeta(source_document=source_document)

        # Phase 1: merge entities (set-union by name)
        existing_ids: dict[str, str] = {}
        for entity in new_entities:
            name = entity.get("name", "")
            if not name:
                continue
            node_id = await self._merge_entity(entity)
            if node_id:
                existing_ids[name] = node_id
                meta.entities_added += 1

        # Phase 2: profile new entities
        if self.llm_adapter:
            await self._profile_and_update_entities(new_entities, existing_ids)

        # Phase 3: merge relations (set-union by from+to+type)
        for rel in new_relations:
            merged = await self._merge_relation(rel, existing_ids)
            if merged:
                meta.relations_added += 1

        # Phase 4: profile new relations
        if self.llm_adapter:
            await self._profile_and_update_relations(new_relations, existing_ids)

        return meta

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _extract_entities(self, text: str) -> tuple:
        if not self.llm_adapter:
            return [], []

        prompt = (
            "从以下文本中提取实体和关系，返回JSON格式：\n"
            '{"entities": [{"name": "实体名", '
            '"type": "Person|Organization|Concept|Event|Document|Topic", '
            '"description": "描述"}], '
            '"relations": [{"from_entity": "源实体", "to_entity": "目标实体", '
            '"relation_type": "RELATED_TO|CONTAINS|MENTIONS|DEPENDS_ON|CREATED_BY", '
            '"description": "描述"}]}\n\n'
            f"文本：\n{text[:2000]}"
        )

        try:
            response = await self.llm_adapter.chat(
                messages=[{"role": "user", "content": prompt}],
                model=None,
                temperature=0.1,
                max_tokens=2000,
            )
            content = response.content
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(content[start:end])
                entities = self._validate_entities(data.get("entities", []))
                relations = self._validate_relations(data.get("relations", []))
                return entities, relations
        except Exception as e:
            logger.warning("Failed to extract entities via LLM: %s", e)
        return [], []

    @staticmethod
    def _validate_entities(raw: list) -> list[dict]:
        """Validate and sanitize LLM-returned entity list.

        Each entity must have ``name`` (str, max 200 chars) and ``type``
        (str matching identifier pattern). Invalid entries are skipped
        with a warning log.
        """
        if not isinstance(raw, list):
            return []
        result: list[dict] = []
        for idx, item in enumerate(raw[:_MAX_ENTITIES]):
            if not isinstance(item, dict):
                logger.warning("Skipping non-dict entity at index %d", idx)
                continue
            name = item.get("name")
            if not isinstance(name, str) or not name.strip() or len(name) > 200:
                logger.warning("Skipping entity with invalid name at index %d", idx)
                continue
            etype = item.get("type", "Entity")
            if not isinstance(etype, str) or not _IDENTIFIER_RE.match(etype):
                logger.warning(
                    "Skipping entity '%s' with invalid type '%s'", name, etype,
                )
                continue
            result.append(item)
        return result

    @staticmethod
    def _validate_relations(raw: list) -> list[dict]:
        """Validate and sanitize LLM-returned relation list.

        Each relation must have ``source``/``from_entity``, ``target``/``to_entity``,
        and ``type``/``relation_type`` (all str, type matches identifier pattern).
        Invalid entries are skipped with a warning log.
        """
        if not isinstance(raw, list):
            return []
        result: list[dict] = []
        for idx, item in enumerate(raw[:_MAX_RELATIONS]):
            if not isinstance(item, dict):
                logger.warning("Skipping non-dict relation at index %d", idx)
                continue
            source = item.get("source") or item.get("from_entity")
            target = item.get("target") or item.get("to_entity")
            rel_type = item.get("type") or item.get("relation_type", "RELATED_TO")
            if (
                not isinstance(source, str) or not source.strip()
                or not isinstance(target, str) or not target.strip()
            ):
                logger.warning(
                    "Skipping relation with missing source/target at index %d", idx,
                )
                continue
            if not isinstance(rel_type, str) or not _IDENTIFIER_RE.match(rel_type):
                logger.warning(
                    "Skipping relation '%s->%s' with invalid type '%s'",
                    source, target, rel_type,
                )
                continue
            result.append(item)
        return result

    async def _merge_entity(self, entity: dict) -> Optional[str]:
        """Merge entity into graph using MERGE (idempotent)."""
        name = entity.get("name", "")
        etype = entity.get("type", "Entity")
        description = entity.get("description", "")

        if not name:
            return None

        try:
            props = {"name": name, "description": description, **{
                k: v for k, v in entity.items()
                if k not in ("name", "type", "description") and isinstance(v, (str, int, float, bool))
            }}
            node_id = await self.graph_store.merge_node(
                etype, "name", props,
            )
            return node_id
        except Exception:
            logger.warning("Failed to merge entity '%s'", name)
            return None

    async def _merge_relation(
        self, rel: dict, entity_ids: dict[str, str],
    ) -> bool:
        """Merge a single relation into the graph (idempotent)."""
        from_name = rel.get("from_entity", rel.get("from", ""))
        to_name = rel.get("to_entity", rel.get("to", ""))
        rel_type = rel.get("relation_type", rel.get("type", "RELATED_TO"))

        from_id = entity_ids.get(from_name)
        to_id = entity_ids.get(to_name)
        if not from_id or not to_id:
            return False

        try:
            await self.graph_store.create_relation(
                from_id, to_id, rel_type,
                {"description": rel.get("description", "")},
            )
            return True
        except Exception:
            logger.warning("Failed to merge relation '%s->%s'", from_name, to_name)
            return False

    async def _profile_and_update_entities(
        self,
        entities: list[dict],
        entity_ids: dict[str, str],
    ) -> None:
        """Profile entities with LLM and store the profile in node properties."""
        for entity in entities:
            name = entity.get("name", "")
            node_id = entity_ids.get(name)
            if not node_id:
                continue
            try:
                profile = await self.profile_entity(entity)
                # Store profile as node properties for keyword-based retrieval
                profile_props = {
                    "profile_keywords": json.dumps(
                        profile.keywords, ensure_ascii=False,
                    ),
                    "profile_summary": profile.summary,
                    "profile_attributes": json.dumps(
                        profile.attributes, ensure_ascii=False,
                    ),
                }
                await self._update_entity_profile(node_id, profile_props)
            except Exception as e:
                logger.warning("Failed to profile entity during enrichment: %s", e)
                continue

    async def _profile_and_update_relations(
        self,
        relations: list[dict],
        entity_ids: dict[str, str],
    ) -> None:
        """Profile relations with LLM and store the profile on the edge."""
        for rel in relations:
            from_name = rel.get("from_entity", rel.get("from", ""))
            to_name = rel.get("to_entity", rel.get("to", ""))
            from_id = entity_ids.get(from_name)
            to_id = entity_ids.get(to_name)
            if not from_id or not to_id:
                continue
            try:
                profile = await self.profile_relation(rel)
                profile_props = {
                    "profile_keywords": json.dumps(
                        profile.keywords, ensure_ascii=False,
                    ),
                    "profile_summary": profile.summary,
                    "profile_attributes": json.dumps(
                        profile.attributes, ensure_ascii=False,
                    ),
                }
                # Update relation properties
                await self.graph_store.create_relation(
                    from_id, to_id,
                    rel.get("relation_type", "RELATED_TO"),
                    profile_props,
                )
            except Exception as e:
                logger.warning("Failed to profile relation during enrichment: %s", e)
                continue

    async def _update_entity_profile(
        self, node_id: str, profile_props: dict,
    ) -> None:
        """Persist profile properties on an entity node."""
        try:
            await self.graph_store.create_node("Entity", {
                "_profile_update": node_id,
                **profile_props,
            })
        except Exception as e:
            logger.warning("Failed to update entity profile for node %s: %s", node_id, e)

    # ------------------------------------------------------------------
    # Heuristic fallbacks
    # ------------------------------------------------------------------

    @staticmethod
    def _heuristic_entity_profile(
        name: str, etype: str, description: str,
    ) -> EntityProfile:
        """Generate a basic profile without LLM."""
        # Split description into words as keywords
        words = [w.strip() for w in description.split() if len(w.strip()) > 1]
        keywords = [name] + words[:5]
        return EntityProfile(
            entity_name=name,
            entity_type=etype,
            keywords=keywords,
            summary=description[:100] if description else name,
            attributes={"type": etype},
        )

    @staticmethod
    def _heuristic_relation_profile(
        from_e: str, to_e: str, rel_type: str, description: str,
    ) -> RelationProfile:
        """Generate a basic relation profile without LLM."""
        keywords = [from_e, to_e, rel_type]
        if description:
            words = [w.strip() for w in description.split() if len(w.strip()) > 1]
            keywords.extend(words[:3])
        return RelationProfile(
            from_entity=from_e,
            to_entity=to_e,
            relation_type=rel_type,
            keywords=keywords,
            summary=description[:100] if description else f"{from_e} {rel_type} {to_e}",
            attributes={"type": rel_type},
        )

    @staticmethod
    def _parse_json_response(content: str) -> dict:
        """Extract the first JSON object from a string response."""
        start = content.find("{")
        end = content.rfind("}") + 1
        if start >= 0 and end > start:
            return json.loads(content[start:end])
        return {}
